site_name: FRAM JuLES
site_author: NVE
site_description: >-
  FRAM JuLES API documentation site
  
repo_url: https://github.com/NVE/fram-jules
repo_name: NVE/fram-jules

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github

nav:  
  - index.md
  - reference.md

markdown_extensions:
- tables
- attr_list

plugins:
  - mkdocstrings:
     handlers:
        python:
          options:  
            show_submodules: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: true
  - mike
  - search
  - macros
  - table-reader

extra:
  version:
    provider: mike
  juleslinks:
      jules: https://github.com/NVE/JulES/
  framlinks:
    nve: https://www.nve.no/english/
    fram: https://nve.github.io/fram/
    core: https://nve.github.io/fram-core/
    demo: https://github.com/NVE/fram-demo
    dataset: https://zenodo.org/records/17294467