name: Deploy fram-jules Documentation

on:
#  push:
#    branches:
#      - main
#    paths:
#      - 'docs/**'
#      - 'framjules/**'
#      - 'mkdocs.yml'
  workflow_dispatch:

jobs:
  deploy-docs:
    uses: NVE/fram-shared/.github/workflows/template_publish_docs.yml@main
    permissions:
      contents: write
    with:
      package_name: 'framjules'
      source_paths: '["docs/**", "framjules/**", "mkdocs.yml"]'
